name: Deploy Test Report to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Make sure this is set to allow writing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      # Run tests with pytest and generate the HTML report
      - name: Run Selenium tests with HTML report
        env:
          DISPLAY: :99
        run: |
          pytest -s -v tests/test_google.py --html=reports/test_report.html

      # Prepare report files for deployment
      - name: Prepare report for GitHub Pages
        if: always()
        run: |
          mkdir -p public
          cp -r reports/* public/
          echo '<html><body><h1>Test Report</h1><iframe src="test_report.html" width="100%" height="100%"></iframe></body></html>' > public/index.html

      # Deploy to GitHub Pages using peaceiris/actions-gh-pages
      - name: Deploy Test Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Ensure the GH_TOKEN secret is set
          publish_dir: ./public
          branch: gh-pages  # The branch that GitHub Pages will use
