name: Run Selenium Tests

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          google-chrome --version
          sudo apt install -y chromium-chromedriver
          chromedriver --version
          
          # Check ChromeDriver location and set it in PATH
          CHROMEDRIVER_PATH=$(which chromedriver)
          echo "CHROMEDRIVER_PATH=${CHROMEDRIVER_PATH}" >> $GITHUB_ENV

      - name: Run Selenium tests
        env:
          CHROMEDRIVER_PATH: ${{ env.CHROMEDRIVER_PATH }}
        run: |
          pytest -s -v tests/test_google.py
