name: Run Selenium Tests

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip

          # Install Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

          # Extract Chrome major version
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+(\.[0-9]+)*' | head -1 | cut -d'.' -f1)
          echo "Detected Chrome version: $CHROME_VERSION"

          # Try to get the latest ChromeDriver version for this major version
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build.json" | jq -r --arg CHROME_VERSION "$CHROME_VERSION" '.builds[$CHROME_VERSION] // empty')

          # If no version is found, use the closest stable version
          if [[ -z "$DRIVER_VERSION" ]]; then
            echo "No exact ChromeDriver version found for Chrome $CHROME_VERSION, using latest stable"
            DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE")
          fi

          echo "Using ChromeDriver version: $DRIVER_VERSION"

          # Download and install ChromeDriver
          wget -N "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # Verify ChromeDriver version
          chromedriver --version

      - name: Set ChromeDriver Path
        run: |
          echo "CHROMEDRIVER_PATH=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Run Selenium tests
        env:
          CHROMEDRIVER_PATH: ${{ env.CHROMEDRIVER_PATH }}
        run: |
          pytest -s -v tests/test_google.py
