name: Selenium Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html  # For HTML report generation

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chromedriver@v1
        with:
          chrome-version: stable

      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          sudo Xvfb :99 -ac &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Verify Chrome and ChromeDriver
        run: |
          echo "Chrome version:"
          chrome --version || google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version

      - name: Run Selenium tests with HTML report
        env:
          DISPLAY: :99
        run: |
          echo "Starting Selenium tests..."
          pytest -s -v --html=report.html tests/test_google.py

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()  # Run even if tests fail
        with:
          name: test-report
          path: report.html
          retention-days: 7

      - name: Check test results
        if: failure()
        run: |
          echo "Tests failed! Check the uploaded report for details."
          echo "Chrome version:"
          chrome --version || google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version
          echo "Display variable:"
          echo $DISPLAY
          exit 1
